FROM clojure:tools-deps
ADD . /app
WORKDIR /app
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash
RUN apt-get install -y nodejs
RUN npm install
ENTRYPOINT ["npx","shadow-cljs","watch",":main"]
