version: '3.2'

services:
   db:
     container_name: db
     image: postgres
     environment:
       POSTGRES_DB: app_db
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
     volumes:
       - ./sql/:/docker-entrypoint-initdb.d/
     ports:
       - 5432:5432
     healthcheck:
       test: ["CMD-SHELL", "pg_isready -U postgres"]
       interval: 10s
       timeout: 5s
       retries: 5
